fix: try fix block Build APK via Unity Method #build

diff --git a/.github/workflows/unity-build.yml b/.github/workflows/unity-build.yml
--- a/.github/workflows/unity-build.yml
+++ b/.github/workflows/unity-build.yml
@@ -47,7 +47,11 @@ jobs:
             -manualLicenseFile /root/.local/share/unity3d/Unity/Unity_lic.ulf \
             -quit \
             -projectPath . \
+            -logFile /root/unity.log \
             -executeMethod Plugins.CI.Editor.Builder.BuildAndroidAPK_Dev
+      
+          echo "------ UNITY LOG ------"
+          cat /root/unity.log || echo "❌ Unity log not found"
 
       - name: 🧪 Run Cake pipeline (tests, logs)
         run: |
